#!/usr/bin/env python
"""Generate docs/index.html — the living project notebook (PT-BR study companion).

Curated prose lives in scripts/overview_content.py (edit that file to grow the doc).
Live facts (git timeline, file tree, Phase-1 task progress, stack versions) are read
from the repository here, so the notebook is always in sync with reality.

The HTML is a DERIVED artifact (gitignored): it is regenerated by the post-commit
hook and by the Pages CI workflow. See ADR-07 in the notebook.

Usage:
    python scripts/generate_overview.py        # or: uv run python scripts/generate_overview.py
"""

from __future__ import annotations

import html
import subprocess
import sys
import tomllib
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import overview_content as C  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "index.html"

IGNORE_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".idea",
    ".vscode",
    "data",
    ".claude",
    "node_modules",
    "_site",
    ".ipynb_checkpoints",
}


# --------------------------------------------------------------------------- #
# git / fs helpers
# --------------------------------------------------------------------------- #
def git(*args: str) -> str:
    try:
        r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=True)
        return r.stdout.strip()
    except Exception:
        return ""


def esc(s: object) -> str:
    """Escape values coming from git/fs. Curated content is trusted and NOT escaped."""
    return html.escape(str(s), quote=True)


def get_commits(limit: int = 50) -> list[dict]:
    sep = "\x1f"
    raw = git("log", f"-{limit}", f"--pretty=%h{sep}%ad{sep}%s", "--date=short")
    out: list[dict] = []
    for line in raw.splitlines():
        parts = line.split(sep)
        if len(parts) == 3:
            out.append({"sha": parts[0], "date": parts[1], "subject": parts[2]})
    return out


def count_total_commits() -> int:
    n = git("rev-list", "--count", "HEAD")
    return int(n) if n.isdigit() else 0


def count_source_modules() -> int:
    src = ROOT / "src"
    if not src.exists():
        return 0
    return sum(1 for p in src.rglob("*.py") if p.name != "__init__.py" and p.stat().st_size > 0)


def count_tests() -> int:
    tests = ROOT / "tests"
    if not tests.exists():
        return 0
    n = 0
    for p in tests.rglob("*.py"):
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        n += sum(
            1
            for line in text.splitlines()
            if line.strip().startswith(("def test_", "async def test_"))
        )
    return n


def read_stack_versions() -> dict:
    pp = ROOT / "pyproject.toml"
    info: dict = {"runtime": [], "dev": [], "python": "—"}
    if not pp.exists():
        return info
    try:
        data = tomllib.loads(pp.read_text(encoding="utf-8"))
    except Exception:
        return info
    proj = data.get("project", {})
    info["python"] = proj.get("requires-python", "—")
    info["runtime"] = proj.get("dependencies", [])
    info["dev"] = data.get("dependency-groups", {}).get("dev", [])
    return info


def _task_done(t: dict) -> bool:
    """A task is done if it declares done=True or its key_file exists on disk."""
    if t.get("done"):
        return True
    kf = t.get("key_file")
    return bool(kf) and (ROOT / kf).exists()


def phases_progress() -> list[dict]:
    """Per-phase progress with auto-detected task completion."""
    phases: list[dict] = []
    for ph in C.PHASES:
        rows: list[dict] = []
        done = 0
        for t in ph["tasks"]:
            is_done = _task_done(t)
            done += int(is_done)
            rows.append({**t, "done": is_done, "manual": t.get("key_file") is None})
        phases.append(
            {
                "id": ph["id"],
                "name": ph["name"],
                "status": ph.get("status", "todo"),
                "summary": ph["summary"],
                "done": done,
                "total": len(ph["tasks"]),
                "rows": rows,
            }
        )
    return phases


def current_phase(phases: list[dict]) -> dict:
    """Phase to surface in the status bar: explicit 'current', else the first
    not-yet-complete one, else the last."""
    for ph in phases:
        if ph["status"] == "current":
            return ph
    for ph in phases:
        if ph["done"] < ph["total"]:
            return ph
    return phases[-1]


def build_tree() -> str:
    lines: list[str] = [f"{ROOT.name}/"]

    def walk(d: Path, prefix: str = "") -> None:
        try:
            entries = sorted(
                (
                    e
                    for e in d.iterdir()
                    if e.name not in IGNORE_DIRS
                    and not e.name.endswith(".pyc")
                    and e.name != "index.html"
                ),
                key=lambda e: (e.is_file(), e.name.lower()),
            )
        except Exception:
            return
        for i, e in enumerate(entries):
            last = i == len(entries) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{e.name}{'/' if e.is_dir() else ''}")
            if e.is_dir():
                walk(e, prefix + ("    " if last else "│   "))

    walk(ROOT)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# render
# --------------------------------------------------------------------------- #
def section(id_: str, title: str, inner: str) -> str:
    return f'<section id="{id_}"><h2>{esc(title)}</h2>{inner}</section>'


def render_status(facts: dict) -> str:
    cur = current_phase(facts["phases"])
    done, total = cur["done"], cur["total"]
    pct = round(done / total * 100) if total else 0
    chips = [
        ("commit", facts["head"]),
        ("branch", facts["branch"]),
        ("commits", facts["total_commits"]),
        ("módulos", facts["modules"]),
        ("testes", facts["tests"]),
        ("python", facts["versions"]["python"]),
    ]
    chip_html = "".join(
        f'<span class="chip"><span class="chip-k">{esc(k)}</span>'
        f'<span class="chip-v">{esc(v)}</span></span>'
        for k, v in chips
    )
    return f"""
<header class="status">
  <div class="status-row">
    <div class="brand"><span class="dot"></span><strong>{esc(C.PROJECT["name"])}</strong>
      <span class="sub">caderno de bordo</span></div>
    <div class="chips">{chip_html}</div>
  </div>
  <div class="progress">
    <div class="progress-label">Fase {cur["id"]} · {done}/{total} tasks</div>
    <div class="bar"><div class="bar-fill" style="width:{pct}%"></div></div>
  </div>
</header>"""


NAV = """
<nav class="toc">
  <a href="#visao">Visão</a><a href="#arquitetura">Arquitetura</a>
  <a href="#stack">Stack</a><a href="#decisoes">Decisões</a>
  <a href="#glossario">Glossário</a><a href="#estrutura">Estrutura</a>
  <a href="#roadmap">Roadmap</a><a href="#timeline">Timeline</a>
  <a href="#diario">Diário</a><a href="#rodar">Rodar</a>
</nav>"""


def render_overview() -> str:
    p = C.PROJECT
    return section(
        "visao",
        "Visão geral",
        f'<p class="lead">{p["tagline"]}</p>'
        f"<h3>O problema</h3><p>{p['problem']}</p>"
        f"<h3>O objetivo</h3><p>{p['goal']}</p>",
    )


def render_pipeline() -> str:
    boxes = []
    for i, s in enumerate(C.PIPELINE):
        arrow = '<span class="arrow">→</span>' if i else ""
        boxes.append(
            f'{arrow}<div class="pbox"><div class="pbox-stage">{esc(s["stage"])}</div>'
            f'<div class="pbox-label">{esc(s["label"])}</div></div>'
        )
    flow = f'<div class="pipeline">{"".join(boxes)}</div>'
    detail = "".join(
        f'<div class="pstep"><code>{esc(s["stage"])}</code> · <strong>{esc(s["label"])}</strong>'
        f"<p>{s['desc']}</p></div>"
        for s in C.PIPELINE
    )
    return section(
        "arquitetura",
        "Arquitetura — o pipeline de dados",
        flow + f'<div class="psteps">{detail}</div>',
    )


def render_stack(versions: dict) -> str:
    rows = "".join(
        f'<tr><td class="tool">{s["name"]}</td><td>{s["role"]}</td><td>{s["why"]}</td></tr>'
        for s in C.STACK
    )
    table = (
        '<table class="stack"><thead><tr><th>Ferramenta</th><th>Papel</th>'
        f"<th>Por quê</th></tr></thead><tbody>{rows}</tbody></table>"
    )
    deps = ", ".join(esc(d) for d in versions["runtime"]) or "—"
    dev = ", ".join(esc(d) for d in versions["dev"]) or "—"
    live = (
        f'<p class="muted small">Do <code>pyproject.toml</code> (vivo) — runtime: '
        f"<code>{deps}</code> · dev: <code>{dev}</code> · "
        f"python <code>{esc(versions['python'])}</code></p>"
    )
    return section("stack", "Stack & ferramentas", table + live)


def render_adrs() -> str:
    cards = "".join(
        f'<article class="adr"><div class="adr-head">'
        f'<span class="adr-id">{esc(a["id"])}</span>'
        f'<span class="adr-status">{a["status"]}</span></div>'
        f"<h3>{a['title']}</h3><dl>"
        f"<dt>Contexto</dt><dd>{a['context']}</dd>"
        f"<dt>Decisão</dt><dd>{a['decision']}</dd>"
        f"<dt>Alternativa descartada</dt><dd>{a['alternative']}</dd>"
        f"<dt>Trade-off</dt><dd>{a['tradeoff']}</dd></dl></article>"
        for a in C.ADRS
    )
    return section("decisoes", "Decisões (ADRs)", f'<div class="adrs">{cards}</div>')


def render_glossary() -> str:
    items = "".join(f"<dt>{esc(t)}</dt><dd>{d}</dd>" for t, d in C.GLOSSARY)
    return section("glossario", "Glossário de domínio", f'<dl class="glossary">{items}</dl>')


def render_tree(tree: str) -> str:
    return section("estrutura", "Estrutura de arquivos", f'<pre class="tree">{esc(tree)}</pre>')


_PHASE_BADGE = {"done": "concluída", "current": "em andamento", "todo": "planejada"}


def render_roadmap(phases: list[dict]) -> str:
    blocks = []
    for ph in phases:
        items = []
        for r in ph["rows"]:
            cls = "done" if r["done"] else "todo"
            mark = "✓" if r["done"] else "○"
            items.append(
                f'<li class="{cls}"><span class="mark">{mark}</span>'
                f'<span class="tnum">{r["n"]:02d}</span> {esc(r["title"])}</li>'
            )
        checklist = f'<ol class="tasks">{"".join(items)}</ol>'
        badge = _PHASE_BADGE.get(ph["status"], "")
        blocks.append(
            f'<div class="phase phase-{esc(ph["status"])}">'
            f'<div class="phase-head"><h3>{esc(ph["name"])}</h3>'
            f'<span class="phase-badge">{ph["done"]}/{ph["total"]} · {esc(badge)}</span></div>'
            f'<p class="phase-sum">{ph["summary"]}</p>{checklist}</div>'
        )
    return section("roadmap", "Roadmap", "".join(blocks))


def render_timeline(commits: list[dict]) -> str:
    if not commits:
        inner = '<p class="muted">Sem commits ainda.</p>'
    else:
        items = "".join(
            f'<li><span class="csha">{esc(c["sha"])}</span>'
            f'<span class="cdate">{esc(c["date"])}</span>'
            f'<span class="csub">{esc(c["subject"])}</span></li>'
            for c in commits
        )
        inner = f'<ul class="timeline">{items}</ul>'
    return section("timeline", "Timeline de commits", inner)


def render_diary() -> str:
    items = "".join(
        f'<article class="entry"><div class="entry-date">{esc(e["date"])}</div>'
        f"<h3>{esc(e['title'])}</h3><p>{e['body']}</p></article>"
        for e in C.DIARY
    )
    return section("diario", "Diário de bordo", f'<div class="diary">{items}</div>')


HOWTO = """<pre class="code"># instalar deps (cria .venv a partir do uv.lock)
uv sync

# rodar os testes com cobertura
uv run pytest

# regenerar este caderno manualmente
uv run python scripts/generate_overview.py

# ativar o hook que regenera a cada commit (uma vez por clone)
git config core.hooksPath .githooks</pre>
<p class="muted small">Este HTML é um artefato gerado (ADR-07): não é versionado e é
recriado pelo hook <code>post-commit</code> e pelo workflow de Pages.</p>"""


def render_howto() -> str:
    return section("rodar", "Como rodar / regenerar", HOWTO)


def render_footer(facts: dict) -> str:
    return (
        f'<footer class="foot">Gerado em {esc(facts["generated_at"])} · '
        f"commit {esc(facts['head'])} · branch {esc(facts['branch'])} · "
        f"fonte: <code>scripts/generate_overview.py</code></footer>"
    )


def page(body: str) -> str:
    return (
        '<!doctype html>\n<html lang="pt-BR">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{esc(C.PROJECT['name'])} · Caderno de bordo</title>\n"
        f"<style>{CSS}</style>\n</head>\n<body>\n{body}\n</body>\n</html>\n"
    )


def main() -> int:
    versions = read_stack_versions()
    facts = {
        "head": git("rev-parse", "--short", "HEAD") or "—",
        "branch": git("rev-parse", "--abbrev-ref", "HEAD") or "—",
        "total_commits": count_total_commits(),
        "modules": count_source_modules(),
        "tests": count_tests(),
        "versions": versions,
        "phases": phases_progress(),
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
    }
    body = "\n".join(
        [
            render_status(facts),
            '<main class="wrap">',
            NAV,
            render_overview(),
            render_pipeline(),
            render_stack(versions),
            render_adrs(),
            render_glossary(),
            render_tree(build_tree()),
            render_roadmap(facts["phases"]),
            render_timeline(get_commits()),
            render_diary(),
            render_howto(),
            render_footer(facts),
            "</main>",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(page(body), encoding="utf-8")
    cur = current_phase(facts["phases"])
    print(
        f"Wrote {OUTPUT.relative_to(ROOT)} — fase {cur['id']} {cur['done']}/{cur['total']}, "
        f"{facts['total_commits']} commits, {facts['tests']} tests"
    )
    return 0


CSS = """
:root{--bg:#f4f0e8;--surface:#fffdf9;--ink:#211d17;--muted:#6f665b;
--accent:#136b64;--accent-2:#b1521d;--border:#e6ddcf;--done:#136b64;
--shadow:0 1px 3px rgba(30,20,10,.06),0 8px 24px rgba(30,20,10,.05)}
*{box-sizing:border-box}html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--ink);font-size:18px;line-height:1.65;
font-family:Georgia,"Iowan Old Style","Palatino Linotype",serif;-webkit-font-smoothing:antialiased}
code,pre{font-family:"SF Mono","Cascadia Code","JetBrains Mono",Consolas,monospace}
code{background:#efe9dd;padding:.08em .35em;border-radius:4px;font-size:.85em}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
.status{position:sticky;top:0;z-index:10;background:var(--surface);
border-bottom:1px solid var(--border);padding:.7rem clamp(1rem,4vw,3rem)}
.status-row{display:flex;flex-wrap:wrap;gap:1rem;align-items:center;justify-content:space-between;
max-width:980px;margin:0 auto}
.brand{display:flex;align-items:center;gap:.5rem}.brand strong{font-size:1.05rem}
.brand .sub{color:var(--muted);font-style:italic;font-size:.85rem}
.dot{width:9px;height:9px;border-radius:50%;background:var(--accent);box-shadow:0 0 0 3px rgba(19,107,100,.18)}
.chips{display:flex;flex-wrap:wrap;gap:.4rem}
.chip{display:inline-flex;gap:.35rem;align-items:baseline;background:var(--bg);
border:1px solid var(--border);border-radius:999px;padding:.15rem .6rem;font-size:.78rem}
.chip-k{color:var(--muted);text-transform:uppercase;letter-spacing:.04em;font-size:.68rem}
.chip-v{font-family:monospace;font-weight:600}
.progress{max-width:980px;margin:.55rem auto 0;display:flex;align-items:center;gap:.8rem}
.progress-label{font-size:.78rem;color:var(--muted);white-space:nowrap}
.bar{flex:1;height:7px;background:#e9e1d3;border-radius:99px;overflow:hidden}
.bar-fill{height:100%;background:linear-gradient(90deg,var(--accent),#1c8a80)}
.wrap{max-width:820px;margin:0 auto;padding:0 clamp(1rem,4vw,2rem) 5rem}
.toc{position:sticky;top:84px;display:flex;flex-wrap:wrap;gap:.4rem .9rem;padding:.7rem 0;
margin-bottom:1rem;border-bottom:1px solid var(--border);font-family:monospace;font-size:.8rem;background:var(--bg)}
section{padding:2.2rem 0;border-bottom:1px solid var(--border)}
section>h2{font-size:1.6rem;margin:.2rem 0 1rem;letter-spacing:-.01em}
h3{font-size:1.15rem;margin:1.4rem 0 .4rem}
.lead{font-size:1.2rem;color:#3a342b;font-style:italic}
.muted{color:var(--muted)}.small{font-size:.85rem}p{margin:.5rem 0}
.pipeline{display:flex;flex-wrap:wrap;align-items:center;gap:.4rem;margin:1rem 0 1.4rem;font-family:monospace}
.pbox{background:var(--surface);border:1px solid var(--border);border-radius:10px;
padding:.5rem .7rem;box-shadow:var(--shadow);min-width:96px}
.pbox-stage{font-size:.65rem;text-transform:uppercase;letter-spacing:.06em;color:var(--accent-2)}
.pbox-label{font-weight:600;font-size:.82rem}.arrow{color:var(--muted);font-size:1.1rem}
.psteps{display:grid;gap:.5rem}
.pstep{background:var(--surface);border:1px solid var(--border);border-left:3px solid var(--accent);
border-radius:8px;padding:.5rem .8rem}.pstep p{margin:.2rem 0 0;font-size:.92rem;color:#403930}
table{width:100%;border-collapse:collapse;margin:.6rem 0;font-size:.92rem}
.stack td,.stack th{text-align:left;vertical-align:top;padding:.5rem .6rem;border-bottom:1px solid var(--border)}
.stack th{font-size:.72rem;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}
.stack .tool{font-family:monospace;font-weight:700;color:var(--accent)}
.adrs{display:grid;gap:1rem}
.adr{background:var(--surface);border:1px solid var(--border);border-radius:12px;
padding:1rem 1.2rem;box-shadow:var(--shadow)}
.adr-head{display:flex;justify-content:space-between;align-items:center}
.adr-id{font-family:monospace;font-weight:700;color:var(--accent-2);font-size:.8rem}
.adr-status{font-size:.72rem;background:rgba(19,107,100,.1);color:var(--accent);padding:.1rem .55rem;border-radius:99px}
.adr h3{margin:.3rem 0 .6rem;font-size:1.05rem}
.adr dl{display:grid;grid-template-columns:auto 1fr;gap:.25rem .9rem;margin:0;font-size:.92rem}
.adr dt{font-weight:700;color:var(--muted);font-size:.8rem;text-transform:uppercase;letter-spacing:.03em;padding-top:.15rem}
.adr dd{margin:0}
.glossary{display:grid;grid-template-columns:auto 1fr;gap:.4rem 1rem;font-size:.92rem}
.glossary dt{font-weight:700;color:var(--accent);font-family:monospace;font-size:.85rem}
.glossary dd{margin:0;padding-bottom:.45rem;border-bottom:1px dotted var(--border)}
.tree,.code{background:#1f1b16;color:#e9e1d3;border-radius:10px;padding:1rem 1.2rem;
overflow-x:auto;font-size:.82rem;line-height:1.5}
.tasks{list-style:none;padding:0;margin:.4rem 0;display:grid;gap:.25rem}
.tasks li{display:flex;align-items:baseline;gap:.5rem;padding:.3rem .5rem;border-radius:6px;font-size:.92rem}
.tasks li.done{background:rgba(19,107,100,.07)}.tasks .mark{font-weight:700}
.tasks li.done .mark{color:var(--done)}.tasks li.todo .mark,.tasks li.manual .mark{color:#c2b8a6}
.tasks .tnum{font-family:monospace;color:var(--muted);font-size:.8rem}.tasks li.done .tnum{color:var(--accent)}
.future{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:.7rem 1rem;margin-top:.6rem}
.future h3{margin:0 0 .2rem;font-size:1rem}.future p{margin:0;font-size:.9rem;color:#403930}
.phase{background:var(--surface);border:1px solid var(--border);border-left:4px solid var(--border);
border-radius:10px;padding:.8rem 1.1rem;margin-top:.9rem;box-shadow:var(--shadow)}
.phase-done{border-left-color:var(--done)}.phase-current{border-left-color:var(--accent-2)}
.phase-head{display:flex;justify-content:space-between;align-items:baseline;gap:1rem;flex-wrap:wrap}
.phase-head h3{margin:0;font-size:1.08rem}
.phase-badge{font-family:monospace;font-size:.72rem;color:var(--muted);white-space:nowrap}
.phase-current .phase-badge{color:var(--accent-2);font-weight:700}
.phase-sum{margin:.3rem 0 .5rem;font-size:.9rem;color:#403930}
.timeline{list-style:none;padding:0;margin:.4rem 0;border-left:2px solid var(--border)}
.timeline li{position:relative;padding:.35rem 0 .35rem 1.2rem;font-size:.9rem}
.timeline li::before{content:"";position:absolute;left:-5px;top:.7rem;width:8px;height:8px;border-radius:50%;background:var(--accent)}
.csha{font-family:monospace;color:var(--accent-2);margin-right:.5rem}
.cdate{font-family:monospace;color:var(--muted);font-size:.8rem;margin-right:.6rem}
.diary{display:grid;gap:.9rem}
.entry{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:.9rem 1.1rem}
.entry-date{font-family:monospace;font-size:.78rem;color:var(--accent-2)}
.entry h3{margin:.15rem 0 .35rem;font-size:1.05rem}.entry p{margin:0;font-size:.93rem}
.foot{max-width:820px;margin:0 auto;padding:2rem clamp(1rem,4vw,2rem);color:var(--muted);font-size:.82rem;font-family:monospace}
@media(max-width:560px){body{font-size:16px}.adr dl,.glossary{grid-template-columns:1fr}.adr dt{padding-top:.4rem}}
"""


if __name__ == "__main__":
    raise SystemExit(main())
